#!/usr/bin/env bash
#
# evaluator-jw.sh — Issue #268 full-season validation matrix (Scenarios A & B)
#
# Runs the rewritten jack_bot.py through the REAL containerized engine over full
# historical seasons and records the median final standing. This is the engine-driven
# source of truth ("is my bot good"), per CLAUDE.md §7/§8 — a wheel build alone does
# not exercise the runtime path.
#
#   Scenario A (baseline):  jack_bot vs a 13-team standard-bot field, random draft order.
#   Scenario B (QB-run):    jack_bot vs a 13-team QB-FIRST field (bots/nfl2025/qb_first_bot.py),
#                           with the candidate PINNED to draft slots 1 / 7 / 14 (issue #267).
#
# Why the seed varies per run in Scenario B:
#   Pinning the slot with a FIXED seed makes the whole draft order reproducible, and the
#   season is then deterministic (historical weekly_stats + deterministic bot logic) — so 5
#   runs at one slot with one seed would be 5 IDENTICAL seasons (no median). To get a real
#   median per slot we hold the candidate's slot fixed and vary the seed per run (SEED_BASE..
#   SEED_BASE+RUNS-1), i.e. 5 different opponent arrangements drafting from the same slot.
#   Scenario A needs no seed: it uses the engine's random order, which varies each run.
#
# Usage:
#   ./evaluator-jw.sh                 # full matrix: A=5 runs, B=slots 1/7/14 x5, seeds 42..46
#   RUNS=3 ./evaluator-jw.sh          # 3 runs per scenario/slot
#   SLOTS="1 14" ./evaluator-jw.sh    # only pin slots 1 and 14
#   SKIP_BUILD=1 ./evaluator-jw.sh    # skip `make build-docker` (image already current)
#
# Requires: a running Docker daemon (the py_grpc_server image is built here), Go, and the
# tracked data/game_states/<YEAR>/season.db. Each run copies season.db to scratch year 2999
# (gitignored) so the tracked DB is never mutated.
#
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# ---- config (override via env) ----
YEAR="${YEAR:-2025}"
RUNS="${RUNS:-5}"
SEED_BASE="${SEED_BASE:-42}"
read -ra SLOTS <<< "${SLOTS:-1 7 14}"
SKIP_BUILD="${SKIP_BUILD:-0}"

CANDIDATE="bots/nfl2025/jack_bot.py"
STD_BASELINE="bots/nfl2025/standard-bot.py"
QB_BASELINE="bots/nfl2025/qb_first_bot.py"

TS="$(date +%Y%m%d-%H%M%S)"
LOGDIR="eval-logs/$TS"
mkdir -p "$LOGDIR"
RESULTS="docs/issue-268-results.md"
EVAL_BIN="$LOGDIR/evaluate"

# DOCKER_HOST resolution mirrors the Makefile `evaluate-bot` target.
export DOCKER_HOST="${DOCKER_HOST:-$(docker context inspect -f '{{.Endpoints.docker.Host}}' 2>/dev/null)}"

echo "==> evaluator-jw | year=$YEAR runs=$RUNS seed_base=$SEED_BASE slots=${SLOTS[*]}"
echo "==> logs: $LOGDIR"

# ---- sanity ----
for f in "$CANDIDATE" "$STD_BASELINE" "$QB_BASELINE"; do
  [[ -f "$f" ]] || { echo "FATAL: missing $f" >&2; exit 1; }
done
[[ -f "data/game_states/$YEAR/season.db" ]] || {
  echo "FATAL: data/game_states/$YEAR/season.db not found (run: make bootstrap-data-build-season YEAR=$YEAR)" >&2
  exit 1
}

# ---- build image + evaluator binary once ----
if [[ "$SKIP_BUILD" != "1" ]]; then
  echo "==> make build-docker"
  make build-docker 2>&1 | tee "$LOGDIR/build-docker.log" || { echo "FATAL: build-docker failed" >&2; exit 1; }
fi
echo "==> go build ./pkg/cmd/evaluate"
go build -o "$EVAL_BIN" ./pkg/cmd/evaluate || { echo "FATAL: evaluator build failed" >&2; exit 1; }

# ---- helpers ----
# median <num...> -> prints median (integer for odd count, .5 possible for even); "NA" if empty
median() {
  [[ $# -eq 0 ]] && { echo "NA"; return; }
  printf '%s\n' "$@" | sort -n | awk '
    {a[NR]=$1}
    END{ if(NR%2){print a[(NR+1)/2]} else {m=(a[NR/2]+a[NR/2+1])/2; if(m==int(m)) printf "%d\n",m; else printf "%.1f\n",m} }'
}

# run_one <logfile> <evaluator-flags...> -> echoes finish integer, or "FAIL"
run_one() {
  local lf="$1"; shift
  if "$EVAL_BIN" "$@" >"$lf" 2>&1; then
    local fin
    fin="$(grep -oE 'finished #[0-9]+' "$lf" | head -1 | grep -oE '[0-9]+')"
    [[ -n "$fin" ]] && echo "$fin" || echo "FAIL"
  else
    echo "FAIL"
  fi
}

# ---- results doc header (truncates any prior run) ----
{
  echo "# Issue #268 — full-season validation results"
  echo
  echo "_Generated by \`evaluator-jw.sh\` on $(date '+%Y-%m-%d %H:%M:%S %Z')._"
  echo
  echo "- Candidate: \`$CANDIDATE\` (the 2026 rewrite)"
  echo "- Engine-driven, full historical season ($YEAR): draft → weekly waivers + scoring → playoffs."
  echo "- Finish = regular-season standing out of 14 (1 = best). Neutral midpoint = 7.5."
  echo "- Runs per scenario/slot: $RUNS. Logs: \`$LOGDIR/\`."
  echo
  echo "## Pre-checks (CLAUDE.md §8 runtime path)"
  echo
  echo "- New QB-first baseline fixture \`bots/nfl2025/qb_first_bot.py\` exists; no existing user bot edited."
  echo "- Container import: the literal \`docker run ... python3 -c 'import bot'\` cannot pass in this repo"
  echo "  because no default \`bot.py\` is shipped — the bot only exists at runtime when the engine writes"
  echo "  \`/tmp/bot.py\`. The runtime-faithful check (mount the bot as the container's \`bot.py\`, as the"
  echo "  engine does) passes, and every full season below loads jack_bot through that same path."
  echo
} > "$RESULTS"

overall_status=0

# ---- Scenario A ----
echo
echo "######## Scenario A: jack_bot vs standard-bot field (random order) ########"
A_FIN=(); A_FAIL=0
for ((r=1; r<=RUNS; r++)); do
  lf="$LOGDIR/A_run${r}.log"
  echo "==> Scenario A run $r/$RUNS ..."
  fin="$(run_one "$lf" -bot="$CANDIDATE" -baseline="$STD_BASELINE" -year="$YEAR" -runs=1)"
  if [[ "$fin" == "FAIL" ]]; then echo "    run $r FAILED (see $lf)"; A_FAIL=$((A_FAIL+1)); overall_status=1
  else echo "    finish: #$fin"; A_FIN+=("$fin"); fi
done
A_MED="$(median "${A_FIN[@]:-}")"
{
  echo "## Scenario A — baseline (standard-bot field, random draft order)"
  echo
  echo "| Run | Finish |"
  echo "|----:|-------:|"
  for ((r=1; r<=RUNS; r++)); do
    v="${A_FIN[$((r-1))]:-FAIL}"; echo "| $r | #$v |"
  done
  echo
  echo "- **Median finish: #$A_MED**${A_FAIL:+  (failed runs: $A_FAIL)}"
  echo
} >> "$RESULTS"
echo "==> Scenario A median finish: #$A_MED"

# ---- Scenario B ----
echo
echo "######## Scenario B: jack_bot vs QB-first field, pinned slots ${SLOTS[*]} ########"
{
  echo "## Scenario B — QB-run stress (qb_first_bot field, candidate pinned per slot)"
  echo
  echo "Seed varies per run (\`$SEED_BASE\`..\`$((SEED_BASE+RUNS-1))\`) so each run is a distinct opponent"
  echo "arrangement drafting from the same pinned slot; the candidate's slot is held fixed."
  echo
} >> "$RESULTS"
declare -a B_SLOT_MED=()
for slot in "${SLOTS[@]}"; do
  echo "==> Slot $slot:"
  S_FIN=(); S_FAIL=0
  for ((r=1; r<=RUNS; r++)); do
    seed=$((SEED_BASE + r - 1))
    lf="$LOGDIR/B_slot${slot}_seed${seed}.log"
    echo "    slot $slot run $r/$RUNS (seed $seed) ..."
    fin="$(run_one "$lf" -bot="$CANDIDATE" -baseline="$QB_BASELINE" -year="$YEAR" -runs=1 -draft_slot="$slot" -seed="$seed")"
    if [[ "$fin" == "FAIL" ]]; then echo "      FAILED (see $lf)"; S_FAIL=$((S_FAIL+1)); overall_status=1
    else echo "      finish: #$fin"; S_FIN+=("$fin"); fi
  done
  S_MED="$(median "${S_FIN[@]:-}")"
  B_SLOT_MED+=("slot $slot → #$S_MED")
  {
    echo "### Slot $slot"
    echo
    echo "| Run | Seed | Finish |"
    echo "|----:|-----:|-------:|"
    for ((r=1; r<=RUNS; r++)); do
      seed=$((SEED_BASE + r - 1)); v="${S_FIN[$((r-1))]:-FAIL}"
      echo "| $r | $seed | #$v |"
    done
    echo
    echo "- **Slot $slot median finish: #$S_MED**${S_FAIL:+  (failed runs: $S_FAIL)}"
    echo
  } >> "$RESULTS"
  echo "==> Slot $slot median finish: #$S_MED"
done

# ---- summary + human-judgment stub ----
{
  echo "## Summary"
  echo
  echo "- Scenario A median: **#$A_MED**"
  for line in "${B_SLOT_MED[@]}"; do echo "- Scenario B $line"; done
  echo
  echo "## Human judgment (HITL — fill in)"
  echo
  echo "Issue #268 asks for directional improvement / no regression. Compare the medians above"
  echo "against expectations (neutral = #7.5; lower is better). Record the call here:"
  echo
  echo "- [ ] No regression vs prior behavior"
  echo "- [ ] Directional improvement observed"
  echo "- Notes:"
  echo
} >> "$RESULTS"

echo
echo "==> DONE. Results written to $RESULTS"
echo "==> Scenario A median: #$A_MED"
for line in "${B_SLOT_MED[@]}"; do echo "==> Scenario B $line"; done
[[ "$overall_status" -ne 0 ]] && echo "==> WARNING: one or more runs FAILED — see $LOGDIR/ logs." >&2
exit "$overall_status"
