// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.25.2
// source: pkg/common/proto/agent.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerStatus_Availability int32

const (
	PlayerStatus_AVAILABLE PlayerStatus_Availability = 0
	PlayerStatus_DRAFTED   PlayerStatus_Availability = 1
	PlayerStatus_ON_HOLD   PlayerStatus_Availability = 2
)

// Enum value maps for PlayerStatus_Availability.
var (
	PlayerStatus_Availability_name = map[int32]string{
		0: "AVAILABLE",
		1: "DRAFTED",
		2: "ON_HOLD",
	}
	PlayerStatus_Availability_value = map[string]int32{
		"AVAILABLE": 0,
		"DRAFTED":   1,
		"ON_HOLD":   2,
	}
)

func (x PlayerStatus_Availability) Enum() *PlayerStatus_Availability {
	p := new(PlayerStatus_Availability)
	*p = x
	return p
}

func (x PlayerStatus_Availability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus_Availability) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_common_proto_agent_proto_enumTypes[0].Descriptor()
}

func (PlayerStatus_Availability) Type() protoreflect.EnumType {
	return &file_pkg_common_proto_agent_proto_enumTypes[0]
}

func (x PlayerStatus_Availability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus_Availability.Descriptor instead.
func (PlayerStatus_Availability) EnumDescriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{3, 0}
}

type Bot_Source int32

const (
	Bot_LOCAL  Bot_Source = 0
	Bot_REMOTE Bot_Source = 1
)

// Enum value maps for Bot_Source.
var (
	Bot_Source_name = map[int32]string{
		0: "LOCAL",
		1: "REMOTE",
	}
	Bot_Source_value = map[string]int32{
		"LOCAL":  0,
		"REMOTE": 1,
	}
)

func (x Bot_Source) Enum() *Bot_Source {
	p := new(Bot_Source)
	*p = x
	return p
}

func (x Bot_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Bot_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_common_proto_agent_proto_enumTypes[1].Descriptor()
}

func (Bot_Source) Type() protoreflect.EnumType {
	return &file_pkg_common_proto_agent_proto_enumTypes[1]
}

func (x Bot_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Bot_Source.Descriptor instead.
func (Bot_Source) EnumDescriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{4, 0}
}

type LeagueSettings struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NumTeams           uint32                 `protobuf:"varint,1,opt,name=num_teams,json=numTeams,proto3" json:"num_teams,omitempty"`
	SlotsPerTeam       map[string]uint32      `protobuf:"bytes,2,rep,name=slots_per_team,json=slotsPerTeam,proto3" json:"slots_per_team,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	IsSnakeDraft       bool                   `protobuf:"varint,3,opt,name=is_snake_draft,json=isSnakeDraft,proto3" json:"is_snake_draft,omitempty"`
	TotalRounds        uint32                 `protobuf:"varint,4,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	PointsPerReception float32                `protobuf:"fixed32,5,opt,name=points_per_reception,json=pointsPerReception,proto3" json:"points_per_reception,omitempty"`
	Year               uint32                 `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LeagueSettings) Reset() {
	*x = LeagueSettings{}
	mi := &file_pkg_common_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeagueSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeagueSettings) ProtoMessage() {}

func (x *LeagueSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeagueSettings.ProtoReflect.Descriptor instead.
func (*LeagueSettings) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *LeagueSettings) GetNumTeams() uint32 {
	if x != nil {
		return x.NumTeams
	}
	return 0
}

func (x *LeagueSettings) GetSlotsPerTeam() map[string]uint32 {
	if x != nil {
		return x.SlotsPerTeam
	}
	return nil
}

func (x *LeagueSettings) GetIsSnakeDraft() bool {
	if x != nil {
		return x.IsSnakeDraft
	}
	return false
}

func (x *LeagueSettings) GetTotalRounds() uint32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *LeagueSettings) GetPointsPerReception() float32 {
	if x != nil {
		return x.PointsPerReception
	}
	return 0
}

func (x *LeagueSettings) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type PlayerSlot struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AllowedPlayerPositions []string               `protobuf:"bytes,2,rep,name=allowed_player_positions,json=allowedPlayerPositions,proto3" json:"allowed_player_positions,omitempty"`
	AssignedPlayerId       string                 `protobuf:"bytes,3,opt,name=assigned_player_id,json=assignedPlayerId,proto3" json:"assigned_player_id,omitempty"`
	AllowsAnyPosition      bool                   `protobuf:"varint,4,opt,name=allows_any_position,json=allowsAnyPosition,proto3" json:"allows_any_position,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PlayerSlot) Reset() {
	*x = PlayerSlot{}
	mi := &file_pkg_common_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSlot) ProtoMessage() {}

func (x *PlayerSlot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSlot.ProtoReflect.Descriptor instead.
func (*PlayerSlot) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerSlot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerSlot) GetAllowedPlayerPositions() []string {
	if x != nil {
		return x.AllowedPlayerPositions
	}
	return nil
}

func (x *PlayerSlot) GetAssignedPlayerId() string {
	if x != nil {
		return x.AssignedPlayerId
	}
	return ""
}

func (x *PlayerSlot) GetAllowsAnyPosition() bool {
	if x != nil {
		return x.AllowsAnyPosition
	}
	return false
}

type Player struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AllowedPositions []string               `protobuf:"bytes,3,rep,name=allowed_positions,json=allowedPositions,proto3" json:"allowed_positions,omitempty"`
	ProfessionalTeam string                 `protobuf:"bytes,4,opt,name=professional_team,json=professionalTeam,proto3" json:"professional_team,omitempty"`
	PlayerByeWeek    uint32                 `protobuf:"varint,5,opt,name=player_bye_week,json=playerByeWeek,proto3" json:"player_bye_week,omitempty"`
	Rank             uint32                 `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	Tier             uint32                 `protobuf:"varint,7,opt,name=tier,proto3" json:"tier,omitempty"`
	PositionRank     uint32                 `protobuf:"varint,8,opt,name=position_rank,json=positionRank,proto3" json:"position_rank,omitempty"`
	PositionTier     uint32                 `protobuf:"varint,9,opt,name=position_tier,json=positionTier,proto3" json:"position_tier,omitempty"`
	Status           *PlayerStatus          `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	GsisId           string                 `protobuf:"bytes,11,opt,name=gsis_id,json=gsisId,proto3" json:"gsis_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_pkg_common_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Player) GetAllowedPositions() []string {
	if x != nil {
		return x.AllowedPositions
	}
	return nil
}

func (x *Player) GetProfessionalTeam() string {
	if x != nil {
		return x.ProfessionalTeam
	}
	return ""
}

func (x *Player) GetPlayerByeWeek() uint32 {
	if x != nil {
		return x.PlayerByeWeek
	}
	return 0
}

func (x *Player) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Player) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *Player) GetPositionRank() uint32 {
	if x != nil {
		return x.PositionRank
	}
	return 0
}

func (x *Player) GetPositionTier() uint32 {
	if x != nil {
		return x.PositionTier
	}
	return 0
}

func (x *Player) GetStatus() *PlayerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Player) GetGsisId() string {
	if x != nil {
		return x.GsisId
	}
	return ""
}

type PlayerStatus struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	Availability     PlayerStatus_Availability `protobuf:"varint,1,opt,name=availability,proto3,enum=PlayerStatus_Availability" json:"availability,omitempty"`
	PickChosen       uint32                    `protobuf:"varint,2,opt,name=pick_chosen,json=pickChosen,proto3" json:"pick_chosen,omitempty"`
	CurrentTeamBotId string                    `protobuf:"bytes,3,opt,name=current_team_bot_id,json=currentTeamBotId,proto3" json:"current_team_bot_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerStatus) Reset() {
	*x = PlayerStatus{}
	mi := &file_pkg_common_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatus) ProtoMessage() {}

func (x *PlayerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatus.ProtoReflect.Descriptor instead.
func (*PlayerStatus) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerStatus) GetAvailability() PlayerStatus_Availability {
	if x != nil {
		return x.Availability
	}
	return PlayerStatus_AVAILABLE
}

func (x *PlayerStatus) GetPickChosen() uint32 {
	if x != nil {
		return x.PickChosen
	}
	return 0
}

func (x *PlayerStatus) GetCurrentTeamBotId() string {
	if x != nil {
		return x.CurrentTeamBotId
	}
	return ""
}

type Bot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FantasyTeamName       string                 `protobuf:"bytes,2,opt,name=fantasy_team_name,json=fantasyTeamName,proto3" json:"fantasy_team_name,omitempty"`
	Owner                 string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	SourceType            Bot_Source             `protobuf:"varint,4,opt,name=source_type,json=sourceType,proto3,enum=Bot_Source" json:"source_type,omitempty"`
	SourceRepoUsername    string                 `protobuf:"bytes,5,opt,name=source_repo_username,json=sourceRepoUsername,proto3" json:"source_repo_username,omitempty"`
	SourceRepoName        string                 `protobuf:"bytes,6,opt,name=source_repo_name,json=sourceRepoName,proto3" json:"source_repo_name,omitempty"`
	SourcePath            string                 `protobuf:"bytes,7,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	EnvPath               string                 `protobuf:"bytes,8,opt,name=env_path,json=envPath,proto3" json:"env_path,omitempty"`
	CurrentWaiverPriority uint32                 `protobuf:"varint,9,opt,name=current_waiver_priority,json=currentWaiverPriority,proto3" json:"current_waiver_priority,omitempty"`
	GithubEnvName         string                 `protobuf:"bytes,10,opt,name=github_env_name,json=githubEnvName,proto3" json:"github_env_name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Bot) Reset() {
	*x = Bot{}
	mi := &file_pkg_common_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Bot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bot) GetFantasyTeamName() string {
	if x != nil {
		return x.FantasyTeamName
	}
	return ""
}

func (x *Bot) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Bot) GetSourceType() Bot_Source {
	if x != nil {
		return x.SourceType
	}
	return Bot_LOCAL
}

func (x *Bot) GetSourceRepoUsername() string {
	if x != nil {
		return x.SourceRepoUsername
	}
	return ""
}

func (x *Bot) GetSourceRepoName() string {
	if x != nil {
		return x.SourceRepoName
	}
	return ""
}

func (x *Bot) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *Bot) GetEnvPath() string {
	if x != nil {
		return x.EnvPath
	}
	return ""
}

func (x *Bot) GetCurrentWaiverPriority() uint32 {
	if x != nil {
		return x.CurrentWaiverPriority
	}
	return 0
}

func (x *Bot) GetGithubEnvName() string {
	if x != nil {
		return x.GithubEnvName
	}
	return ""
}

type GameState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Players            []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Bots               []*Bot                 `protobuf:"bytes,2,rep,name=bots,proto3" json:"bots,omitempty"`
	LeagueSettings     *LeagueSettings        `protobuf:"bytes,3,opt,name=league_settings,json=leagueSettings,proto3" json:"league_settings,omitempty"`
	CurrentBotTeamId   string                 `protobuf:"bytes,4,opt,name=current_bot_team_id,json=currentBotTeamId,proto3" json:"current_bot_team_id,omitempty"`
	CurrentDraftPick   uint32                 `protobuf:"varint,5,opt,name=current_draft_pick,json=currentDraftPick,proto3" json:"current_draft_pick,omitempty"`
	CurrentFantasyWeek uint32                 `protobuf:"varint,6,opt,name=current_fantasy_week,json=currentFantasyWeek,proto3" json:"current_fantasy_week,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_pkg_common_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GameState) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetBots() []*Bot {
	if x != nil {
		return x.Bots
	}
	return nil
}

func (x *GameState) GetLeagueSettings() *LeagueSettings {
	if x != nil {
		return x.LeagueSettings
	}
	return nil
}

func (x *GameState) GetCurrentBotTeamId() string {
	if x != nil {
		return x.CurrentBotTeamId
	}
	return ""
}

func (x *GameState) GetCurrentDraftPick() uint32 {
	if x != nil {
		return x.CurrentDraftPick
	}
	return 0
}

func (x *GameState) GetCurrentFantasyWeek() uint32 {
	if x != nil {
		return x.CurrentFantasyWeek
	}
	return 0
}

type DraftSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftSelection) Reset() {
	*x = DraftSelection{}
	mi := &file_pkg_common_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftSelection) ProtoMessage() {}

func (x *DraftSelection) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftSelection.ProtoReflect.Descriptor instead.
func (*DraftSelection) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DraftSelection) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type AttemptedFantasyActions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaiverClaims  []*WaiverClaim         `protobuf:"bytes,1,rep,name=waiver_claims,json=waiverClaims,proto3" json:"waiver_claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptedFantasyActions) Reset() {
	*x = AttemptedFantasyActions{}
	mi := &file_pkg_common_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptedFantasyActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptedFantasyActions) ProtoMessage() {}

func (x *AttemptedFantasyActions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptedFantasyActions.ProtoReflect.Descriptor instead.
func (*AttemptedFantasyActions) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AttemptedFantasyActions) GetWaiverClaims() []*WaiverClaim {
	if x != nil {
		return x.WaiverClaims
	}
	return nil
}

type WaiverClaim struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerToDropId string                 `protobuf:"bytes,1,opt,name=player_to_drop_id,json=playerToDropId,proto3" json:"player_to_drop_id,omitempty"`
	PlayerToAddId  string                 `protobuf:"bytes,2,opt,name=player_to_add_id,json=playerToAddId,proto3" json:"player_to_add_id,omitempty"`
	BidAmount      uint32                 `protobuf:"varint,3,opt,name=bid_amount,json=bidAmount,proto3" json:"bid_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WaiverClaim) Reset() {
	*x = WaiverClaim{}
	mi := &file_pkg_common_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaiverClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaiverClaim) ProtoMessage() {}

func (x *WaiverClaim) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_common_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaiverClaim.ProtoReflect.Descriptor instead.
func (*WaiverClaim) Descriptor() ([]byte, []int) {
	return file_pkg_common_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *WaiverClaim) GetPlayerToDropId() string {
	if x != nil {
		return x.PlayerToDropId
	}
	return ""
}

func (x *WaiverClaim) GetPlayerToAddId() string {
	if x != nil {
		return x.PlayerToAddId
	}
	return ""
}

func (x *WaiverClaim) GetBidAmount() uint32 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

var File_pkg_common_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_common_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/common/proto/agent.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc6\x02\n" +
	"\x0eLeagueSettings\x12\x1b\n" +
	"\tnum_teams\x18\x01 \x01(\rR\bnumTeams\x12G\n" +
	"\x0eslots_per_team\x18\x02 \x03(\v2!.LeagueSettings.SlotsPerTeamEntryR\fslotsPerTeam\x12$\n" +
	"\x0eis_snake_draft\x18\x03 \x01(\bR\fisSnakeDraft\x12!\n" +
	"\ftotal_rounds\x18\x04 \x01(\rR\vtotalRounds\x120\n" +
	"\x14points_per_reception\x18\x05 \x01(\x02R\x12pointsPerReception\x12\x12\n" +
	"\x04year\x18\x06 \x01(\rR\x04year\x1a?\n" +
	"\x11SlotsPerTeamEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xb8\x01\n" +
	"\n" +
	"PlayerSlot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\x18allowed_player_positions\x18\x02 \x03(\tR\x16allowedPlayerPositions\x12,\n" +
	"\x12assigned_player_id\x18\x03 \x01(\tR\x10assignedPlayerId\x12.\n" +
	"\x13allows_any_position\x18\x04 \x01(\bR\x11allowsAnyPosition\"\xe9\x02\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12+\n" +
	"\x11allowed_positions\x18\x03 \x03(\tR\x10allowedPositions\x12+\n" +
	"\x11professional_team\x18\x04 \x01(\tR\x10professionalTeam\x12&\n" +
	"\x0fplayer_bye_week\x18\x05 \x01(\rR\rplayerByeWeek\x12\x12\n" +
	"\x04rank\x18\x06 \x01(\rR\x04rank\x12\x12\n" +
	"\x04tier\x18\a \x01(\rR\x04tier\x12#\n" +
	"\rposition_rank\x18\b \x01(\rR\fpositionRank\x12#\n" +
	"\rposition_tier\x18\t \x01(\rR\fpositionTier\x12%\n" +
	"\x06status\x18\n" +
	" \x01(\v2\r.PlayerStatusR\x06status\x12\x17\n" +
	"\agsis_id\x18\v \x01(\tR\x06gsisId\"\xd7\x01\n" +
	"\fPlayerStatus\x12>\n" +
	"\favailability\x18\x01 \x01(\x0e2\x1a.PlayerStatus.AvailabilityR\favailability\x12\x1f\n" +
	"\vpick_chosen\x18\x02 \x01(\rR\n" +
	"pickChosen\x12-\n" +
	"\x13current_team_bot_id\x18\x03 \x01(\tR\x10currentTeamBotId\"7\n" +
	"\fAvailability\x12\r\n" +
	"\tAVAILABLE\x10\x00\x12\v\n" +
	"\aDRAFTED\x10\x01\x12\v\n" +
	"\aON_HOLD\x10\x02\"\x9e\x03\n" +
	"\x03Bot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11fantasy_team_name\x18\x02 \x01(\tR\x0ffantasyTeamName\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12,\n" +
	"\vsource_type\x18\x04 \x01(\x0e2\v.Bot.SourceR\n" +
	"sourceType\x120\n" +
	"\x14source_repo_username\x18\x05 \x01(\tR\x12sourceRepoUsername\x12(\n" +
	"\x10source_repo_name\x18\x06 \x01(\tR\x0esourceRepoName\x12\x1f\n" +
	"\vsource_path\x18\a \x01(\tR\n" +
	"sourcePath\x12\x19\n" +
	"\benv_path\x18\b \x01(\tR\aenvPath\x126\n" +
	"\x17current_waiver_priority\x18\t \x01(\rR\x15currentWaiverPriority\x12&\n" +
	"\x0fgithub_env_name\x18\n" +
	" \x01(\tR\rgithubEnvName\"\x1f\n" +
	"\x06Source\x12\t\n" +
	"\x05LOCAL\x10\x00\x12\n" +
	"\n" +
	"\x06REMOTE\x10\x01\"\x91\x02\n" +
	"\tGameState\x12!\n" +
	"\aplayers\x18\x01 \x03(\v2\a.PlayerR\aplayers\x12\x18\n" +
	"\x04bots\x18\x02 \x03(\v2\x04.BotR\x04bots\x128\n" +
	"\x0fleague_settings\x18\x03 \x01(\v2\x0f.LeagueSettingsR\x0eleagueSettings\x12-\n" +
	"\x13current_bot_team_id\x18\x04 \x01(\tR\x10currentBotTeamId\x12,\n" +
	"\x12current_draft_pick\x18\x05 \x01(\rR\x10currentDraftPick\x120\n" +
	"\x14current_fantasy_week\x18\x06 \x01(\rR\x12currentFantasyWeek\"-\n" +
	"\x0eDraftSelection\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"L\n" +
	"\x17AttemptedFantasyActions\x121\n" +
	"\rwaiver_claims\x18\x01 \x03(\v2\f.WaiverClaimR\fwaiverClaims\"\x80\x01\n" +
	"\vWaiverClaim\x12)\n" +
	"\x11player_to_drop_id\x18\x01 \x01(\tR\x0eplayerToDropId\x12'\n" +
	"\x10player_to_add_id\x18\x02 \x01(\tR\rplayerToAddId\x12\x1d\n" +
	"\n" +
	"bid_amount\x18\x03 \x01(\rR\tbidAmount2\x9b\x01\n" +
	"\fAgentService\x128\n" +
	"\vDraftPlayer\x12\x16.google.protobuf.Empty\x1a\x0f.DraftSelection\"\x00\x12Q\n" +
	"\x1bPerformWeeklyFantasyActions\x12\x16.google.protobuf.Empty\x1a\x18.AttemptedFantasyActions\"\x00B\n" +
	"Z\b.;commonb\x06proto3"

var (
	file_pkg_common_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_common_proto_agent_proto_rawDescData []byte
)

func file_pkg_common_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_common_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_common_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_common_proto_agent_proto_rawDesc), len(file_pkg_common_proto_agent_proto_rawDesc)))
	})
	return file_pkg_common_proto_agent_proto_rawDescData
}

var file_pkg_common_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_common_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_common_proto_agent_proto_goTypes = []any{
	(PlayerStatus_Availability)(0),  // 0: PlayerStatus.Availability
	(Bot_Source)(0),                 // 1: Bot.Source
	(*LeagueSettings)(nil),          // 2: LeagueSettings
	(*PlayerSlot)(nil),              // 3: PlayerSlot
	(*Player)(nil),                  // 4: Player
	(*PlayerStatus)(nil),            // 5: PlayerStatus
	(*Bot)(nil),                     // 6: Bot
	(*GameState)(nil),               // 7: GameState
	(*DraftSelection)(nil),          // 8: DraftSelection
	(*AttemptedFantasyActions)(nil), // 9: AttemptedFantasyActions
	(*WaiverClaim)(nil),             // 10: WaiverClaim
	nil,                             // 11: LeagueSettings.SlotsPerTeamEntry
	(*emptypb.Empty)(nil),           // 12: google.protobuf.Empty
}
var file_pkg_common_proto_agent_proto_depIdxs = []int32{
	11, // 0: LeagueSettings.slots_per_team:type_name -> LeagueSettings.SlotsPerTeamEntry
	5,  // 1: Player.status:type_name -> PlayerStatus
	0,  // 2: PlayerStatus.availability:type_name -> PlayerStatus.Availability
	1,  // 3: Bot.source_type:type_name -> Bot.Source
	4,  // 4: GameState.players:type_name -> Player
	6,  // 5: GameState.bots:type_name -> Bot
	2,  // 6: GameState.league_settings:type_name -> LeagueSettings
	10, // 7: AttemptedFantasyActions.waiver_claims:type_name -> WaiverClaim
	12, // 8: AgentService.DraftPlayer:input_type -> google.protobuf.Empty
	12, // 9: AgentService.PerformWeeklyFantasyActions:input_type -> google.protobuf.Empty
	8,  // 10: AgentService.DraftPlayer:output_type -> DraftSelection
	9,  // 11: AgentService.PerformWeeklyFantasyActions:output_type -> AttemptedFantasyActions
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_common_proto_agent_proto_init() }
func file_pkg_common_proto_agent_proto_init() {
	if File_pkg_common_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_common_proto_agent_proto_rawDesc), len(file_pkg_common_proto_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_common_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_common_proto_agent_proto_depIdxs,
		EnumInfos:         file_pkg_common_proto_agent_proto_enumTypes,
		MessageInfos:      file_pkg_common_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_common_proto_agent_proto = out.File
	file_pkg_common_proto_agent_proto_goTypes = nil
	file_pkg_common_proto_agent_proto_depIdxs = nil
}
