# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\"\x85\x01\n\x10\x46\x61ntasyLandscape\x12\x14\n\x0cmatch_number\x18\x01 \x01(\r\x12!\n\x08settings\x18\x02 \x01(\x0b\x32\x0f.LeagueSettings\x12\x1e\n\x08\x62ot_team\x18\x03 \x01(\x0b\x32\x0c.FantasyTeam\x12\x18\n\x07players\x18\x04 \x03(\x0b\x32\x07.Player\"/\n\x11\x46\x61ntasySelections\x12\x1a\n\x05slots\x18\x01 \x03(\x0b\x32\x0b.PlayerSlot\"6\n\x0b\x46\x61ntasyTeam\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05owner\x18\x03 \x01(\t\"H\n\x0eLeagueSettings\x12\x11\n\tnum_teams\x18\x01 \x01(\r\x12#\n\x0eslots_per_team\x18\x02 \x03(\x0b\x32\x0b.PlayerSlot\"X\n\nPlayerSlot\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x18\x61llowed_player_positions\x18\x02 \x03(\t\x12\x1a\n\x12\x61ssigned_player_id\x18\x03 \x01(\t\"\x86\x01\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\x19\n\x11\x61llowed_positions\x18\x03 \x03(\t\x12\x19\n\x11professional_team\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x17\n\x0f\x66\x61ntasy_team_id\x18\x06 \x01(\r\"b\n\x03\x42ot\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1c\n\x14source_repo_username\x18\x02 \x01(\t\x12\x18\n\x10source_repo_name\x18\x03 \x01(\t\x12\x17\n\x0f\x66\x61ntasy_team_id\x18\x04 \x01(\r2P\n\x0c\x41gentService\x12@\n\x15PerformFantasyActions\x12\x11.FantasyLandscape\x1a\x12.FantasySelections\"\x00\x42\nZ\x08.;commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010.;common'
  _globals['_FANTASYLANDSCAPE']._serialized_start=16
  _globals['_FANTASYLANDSCAPE']._serialized_end=149
  _globals['_FANTASYSELECTIONS']._serialized_start=151
  _globals['_FANTASYSELECTIONS']._serialized_end=198
  _globals['_FANTASYTEAM']._serialized_start=200
  _globals['_FANTASYTEAM']._serialized_end=254
  _globals['_LEAGUESETTINGS']._serialized_start=256
  _globals['_LEAGUESETTINGS']._serialized_end=328
  _globals['_PLAYERSLOT']._serialized_start=330
  _globals['_PLAYERSLOT']._serialized_end=418
  _globals['_PLAYER']._serialized_start=421
  _globals['_PLAYER']._serialized_end=555
  _globals['_BOT']._serialized_start=557
  _globals['_BOT']._serialized_end=655
  _globals['_AGENTSERVICE']._serialized_start=657
  _globals['_AGENTSERVICE']._serialized_end=737
# @@protoc_insertion_point(module_scope)
